export const ACTION_TYPE = {
  SET_USERS_DATA: 'SET_USERS_DATA',
  SET_USER_DATA: 'SET_USER_DATA',
  SET_APP_DATA: 'SET_APP_DATA',
  SET_APP_LOGOUT: 'SET_APP_LOGOUT',
  UPDATE_USERS_DATA: 'UPDATE_USERS_DATA',
};
